#Créer une liste de dictionnaires, où chaque dictionnaire contient des informations sur un client (nom, email, montant dépensé). Minimum 50 entrées

clients = [
    {"nom": "Alice Dupont", "email": "alice.dupont@example.com", "montant_depense": 1000},
    {"nom": "Bob Martin", "email": "bob.martin@example.com", "montant_depense": 1500},
    {"nom": "Claire Lambert", "email": "claire.lambert@example.com", "montant_depense": 800},
    {"nom": "David Lefevre", "email": "david.lefevre@example.com", "montant_depense": 1200},
    {"nom": "Emma Moreau", "email": "emma.moreau@example.com", "montant_depense": 900},
    {"nom": "Franck Rocher", "email": "franck.rocher@example.com", "montant_depense": 1100},
    {"nom": "Gabrielle Girard", "email": "gabrielle.girard@example.com", "montant_depense": 1300},
    {"nom": "Hugo Dufresne", "email": "hugo.dufresne@example.com", "montant_depense": 950},
    {"nom": "Inès Gauthier", "email": "ines.gauthier@example.com", "montant_depense": 850},
    {"nom": "Julien Mercier", "email": "julien.mercier@example.com", "montant_depense": 1200},
    {"nom": "Kelly Bertrand", "email": "kelly.bertrand@example.com", "montant_depense": 1000},
    {"nom": "Lucie Boucher", "email": "lucie.boucher@example.com", "montant_depense": 900},
    {"nom": "Maxime Giroux", "email": "maxime.giroux@example.com", "montant_depense": 1100},
    {"nom": "Nina Chevalier", "email": "nina.chevalier@example.com", "montant_depense": 1300},
    {"nom": "Olivier Tremblay", "email": "olivier.tremblay@example.com", "montant_depense": 850},
    {"nom": "Pauline Lemoine", "email": "pauline.lemoine@example.com", "montant_depense": 950},
    {"nom": "Quentin Deschamps", "email": "quentin.deschamps@example.com", "montant_depense": 1200},
    {"nom": "Rose Perrin", "email": "rose.perrin@example.com", "montant_depense": 900},
    {"nom": "Sylvain Caron", "email": "sylvain.caron@example.com", "montant_depense": 1100},
    {"nom": "Tessa Roy", "email": "tessa.roy@example.com", "montant_depense": 1300},
    {"nom": "Ulysse Lefevre", "email": "ulysse.lefevre@example.com", "montant_depense": 1000},
    {"nom": "Victoria Dubois", "email": "victoria.dubois@example.com", "montant_depense": 800},
    {"nom": "William Henry", "email": "william.henry@example.com", "montant_depense": 950},
    {"nom": "Xavier Bertrand", "email": "xavier.bertrand@example.com", "montant_depense": 1200},
    {"nom": "Yasmine Legrand", "email": "yasmine.legrand@example.com", "montant_depense": 900},
    {"nom": "Zoé Renard", "email": "zoe.renard@example.com", "montant_depense": 1100},
    {"nom": "Adam Moreau", "email": "adam.moreau@example.com", "montant_depense": 1300},
    {"nom": "Béatrice Leclerc", "email": "beatrice.leclerc@example.com", "montant_depense": 850},
    {"nom": "Charles Royer", "email": "charles.royer@example.com", "montant_depense": 950},
    {"nom": "Diane Lefevre", "email": "diane.lefevre@example.com", "montant_depense": 1200},
    {"nom": "Éric Bergeron", "email": "eric.bergeron@example.com", "montant_depense": 900},
    {"nom": "Fiona Mercier", "email": "fiona.mercier@example.com", "montant_depense": 1100},
    {"nom": "Gilles Leroux", "email": "gilles.leroux@example.com", "montant_depense": 1300},
    {"nom": "Hélène Deschamps", "email": "helene.deschamps@example.com", "montant_depense": 1000},
    {"nom": "Ivan Gagnon", "email": "ivan.gagnon@example.com", "montant_depense": 800},
    {"nom": "Jessica Bouchard", "email": "jessica.bouchard@example.com", "montant_depense": 950},
    {"nom": "Karl Martel", "email": "karl.martel@example.com", "montant_depense": 1200},
    {"nom": "Léa Lavoie", "email": "lea.lavoie@example.com", "montant_depense": 900},
    {"nom": "Marc Girard", "email": "marc.girard@example.com", "montant_depense": 1100},
    {"nom": "Nadia Richard", "email": "nadia.richard@example.com", "montant_depense": 1300},
    {"nom": "Olivier Fournier", "email": "olivier.fournier@example.com", "montant_depense": 850},
    {"nom": "Pauline Gosselin", "email": "pauline.gosselin@example.com", "montant_depense": 950},
    {"nom": "Quentin Lemieux", "email": "quentin.lemieux@example.com", "montant_depense": 1200},
    {"nom": "Roxane Leclair", "email": "roxane.leclair@example.com", "montant_depense": 900},
    {"nom": "Samuel Lambert", "email": "samuel.lambert@example.com", "montant_depense": 1100},
    {"nom": "Tania Tremblay", "email": "tania.tremblay@example.com", "montant_depense": 1300},
    {"nom": "Ugo Dufresne", "email": "ugo.dufresne@example.com", "montant_depense": 1000},
    {"nom": "Véronique Dufour", "email": "veronique.dufour@example.com", "montant_depense": 800},
    {"nom": "Willy Lambert", "email": "willy.lambert@example.com", "montant_depense": 950},
    {"nom": "Xavier Tremblay", "email": "xavier.tremblay@example.com", "montant_depense": 1200},
    {"nom": "Yannick Lefevre", "email": "yannick.lefevre@example.com", "montant_depense": 900},
    {"nom": "Zoé Bouchard", "email": "zoe.bouchard@example.com", "montant_depense": 1100},
]





